#!/bin/bash
# product.sh — deterministic operations for .project/product/ promise entries.
# Agents supply the judgment (Promise / Authority / Evidence / Scope);
# this script owns numbering, status flips, checked stamps, and INDEX.md generation.
# Convention: .project/product/README.md
#
# Usage:
#   product.sh new <slug> [--title "..."]   create next entry, print its path
#   product.sh supersede <old-id> <new-id>  mark old superseded by new
#   product.sh amend <old-id> <new-id>      record new as amending old
#   product.sh check <id> [ref]             stamp last-verified date (+ optional git ref)
#   product.sh index                        regenerate INDEX.md from entries
set -euo pipefail

find_project_root() {
    if [ -d ".project" ]; then pwd; return; fi
    local root
    root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
    if [ -n "$root" ] && [ -d "$root/.project" ]; then echo "$root"; return; fi
    echo "Error: no .project/ directory found (run from the repo root)" >&2
    exit 1
}

ROOT="$(find_project_root)"
PRODUCT_DIR="$ROOT/.project/product"
INDEX="$PRODUCT_DIR/INDEX.md"

# field <file> <key> — read a frontmatter value
field() {
    awk -v key="$2" '
        NR==1 && $0=="---" {infm=1; next}
        infm && $0=="---" {exit}
        infm && index($0, key": ")==1 {sub("^"key": ", ""); print; exit}
    ' "$1"
}

# set_field <file> <key> <value> — replace a frontmatter value in place;
# fails loudly if the field is absent (a silent no-op would report success
# without applying the mutation)
set_field() {
    local file="$1" key="$2" value="$3" tmp
    tmp="$(mktemp)"
    if ! awk -v key="$key" -v value="$value" '
        NR==1 && $0=="---" {infm=1; print; next}
        infm && $0=="---" {infm=0; print; next}
        infm && index($0, key": ")==1 {print key": "value; found=1; next}
        {print}
        END {exit found ? 0 : 1}
    ' "$file" > "$tmp"; then
        rm -f "$tmp"
        echo "Error: no frontmatter field '$key' in $file (malformed entry?)" >&2
        exit 1
    fi
    mv "$tmp" "$file"
}

# entry_file <id> — resolve an id to its entry path; ambiguity is an error,
# never a silent pick (mutating an arbitrary duplicate rewrites the wrong entry)
entry_file() {
    local match
    match="$(compgen -G "$PRODUCT_DIR/$1-*.md" || true)"
    if [ -z "$match" ]; then
        echo "Error: no entry with id $1 in $PRODUCT_DIR" >&2
        exit 1
    fi
    if [ "$(echo "$match" | wc -l)" -gt 1 ]; then
        echo "Error: multiple entries share id $1 — resolve the duplicate ids first:" >&2
        echo "$match" >&2
        exit 1
    fi
    echo "$match"
}

regen_index() {
    mkdir -p "$PRODUCT_DIR"
    local f id title surfaces status sup checked line active_lines="" other_lines=""
    for f in "$PRODUCT_DIR"/[0-9][0-9][0-9][0-9]-*.md; do
        [ -e "$f" ] || continue
        id="$(field "$f" id)"
        title="$(field "$f" title)"
        surfaces="$(field "$f" surfaces | tr -d '[]')"
        status="$(field "$f" status)"
        sup="$(field "$f" superseded_by)"
        checked="$(field "$f" checked)"
        line="- $id · $title"
        [ -n "$surfaces" ] && line="$line · surfaces: $surfaces"
        if [ "$status" = "superseded" ] && [ "$sup" != "null" ]; then
            line="$line · superseded → $sup"
        else
            [ "$status" != "active" ] && line="$line · $status"
            [ -n "$checked" ] && [ "$checked" != "null" ] && line="$line · checked: $checked"
        fi
        if [ "$status" = "active" ]; then
            active_lines+="$line"$'\n'
        else
            other_lines+="$line"$'\n'
        fi
    done
    {
        echo "# Product Promises Index"
        echo ""
        echo "<!-- generated by product.sh — do not hand-edit; run 'product.sh index' to rebuild -->"
        echo ""
        printf '%s' "$active_lines"
        if [ -n "$other_lines" ]; then
            echo ""
            printf '%s' "$other_lines"
        fi
    } > "$INDEX"
}

next_free_number() {
    local max=0 f n
    for f in "$PRODUCT_DIR"/[0-9][0-9][0-9][0-9]-*.md; do
        [ -e "$f" ] || continue
        n=$((10#$(basename "$f" | cut -c1-4)))
        [ "$n" -gt "$max" ] && max=$n
    done
    local cand=$((max + 1))
    # collision guard for parallel sessions: take the next unclaimed number
    while compgen -G "$PRODUCT_DIR/$(printf '%04d' "$cand")-*.md" >/dev/null; do
        cand=$((cand + 1))
    done
    printf '%04d' "$cand"
}

cmd_new() {
    local slug="${1:?usage: product.sh new <slug> [--title \"...\"]}"
    shift
    local title=""
    while [ $# -gt 0 ]; do
        case "$1" in
            --title) title="${2:?--title needs a value}"; shift 2 ;;
            *) echo "Error: unknown option $1" >&2; exit 1 ;;
        esac
    done
    [ -n "$title" ] || title="$(echo "$slug" | tr '-' ' ')"
    mkdir -p "$PRODUCT_DIR"
    # serialize allocation + creation: parallel sessions race for the same number,
    # and the free-number scan alone is not an atomic claim
    LOCK="$PRODUCT_DIR/.lock"
    local tries=0
    until mkdir "$LOCK" 2>/dev/null; do
        tries=$((tries + 1))
        if [ "$tries" -ge 100 ]; then
            echo "Error: could not acquire $LOCK — remove it if no other product.sh run is active" >&2
            exit 1
        fi
        sleep 0.05
    done
    trap 'rmdir "$LOCK" 2>/dev/null' EXIT
    local id file date owner
    id="$(next_free_number)"
    file="$PRODUCT_DIR/$id-$slug.md"
    date="$(date '+%Y-%m-%d')"
    owner="$(git config --get user.name 2>/dev/null || echo 'unknown')"
    cat > "$file" <<EOF
---
id: $id
title: $title
date: $date
owner: $owner
status: active
amended_by: []
superseded_by: null
supersedes: null
provenance: "[AGENT]"
surfaces: []
checked: null
---

## Promise

[1-3 sentences, plain language: what the product guarantees, as implemented.
The title above is this promise's one-liner — the index is only as good as it.]

## Authority

- [Graded citations to the durable sources that make this a promise (spec, concept,
  ADR, docs) — or, for a first capture, the [OWNER-VERBATIM] quote with date/context.]

## Evidence

- [Optional, proportional: paths, test names, or "exercised manually <date>".
  Delete this section if the Authority citations already show it. Evidence never
  substitutes for Authority.]

## Scope

[Optional: one or two sentences for partial rollout / flags — never a catalog.
Delete this section if the promise applies unconditionally.]
EOF
    regen_index
    echo "$file"
}

cmd_supersede() {
    local old_id="${1:?usage: product.sh supersede <old-id> <new-id>}"
    local new_id="${2:?usage: product.sh supersede <old-id> <new-id>}"
    if [ "$old_id" = "$new_id" ]; then
        echo "Error: an entry cannot supersede itself" >&2
        exit 1
    fi
    local old_file new_file
    old_file="$(entry_file "$old_id")"
    new_file="$(entry_file "$new_id")"
    if [ "$(field "$old_file" status)" = "superseded" ]; then
        echo "Error: $old_id is already superseded by $(field "$old_file" superseded_by) — supersede that successor instead (overwriting the link would rewrite history)" >&2
        exit 1
    fi
    set_field "$old_file" status superseded
    set_field "$old_file" superseded_by "$new_id"
    set_field "$new_file" supersedes "$old_id"
    regen_index
    echo "$old_id superseded by $new_id"
}

cmd_amend() {
    local old_id="${1:?usage: product.sh amend <old-id> <new-id>}"
    local new_id="${2:?usage: product.sh amend <old-id> <new-id>}"
    if [ "$old_id" = "$new_id" ]; then
        echo "Error: an entry cannot amend itself" >&2
        exit 1
    fi
    local old_file current
    old_file="$(entry_file "$old_id")"
    entry_file "$new_id" >/dev/null
    current="$(field "$old_file" amended_by | tr -d '[]')"
    if [ -n "$current" ]; then
        set_field "$old_file" amended_by "[$current, $new_id]"
    else
        set_field "$old_file" amended_by "[$new_id]"
    fi
    # superseded outranks amended; don't downgrade
    if [ "$(field "$old_file" status)" = "active" ]; then
        set_field "$old_file" status amended
    fi
    regen_index
    echo "$old_id amended by $new_id"
}

cmd_check() {
    local id="${1:?usage: product.sh check <id> [ref]}"
    local ref="${2:-}"
    local file stamp
    file="$(entry_file "$id")"
    stamp="$(date '+%Y-%m-%d')"
    [ -n "$ref" ] && stamp="$stamp @ $ref"
    set_field "$file" checked "$stamp"
    regen_index
    echo "$id checked: $stamp"
}

case "${1:-}" in
    new)       shift; cmd_new "$@" ;;
    supersede) shift; cmd_supersede "$@" ;;
    amend)     shift; cmd_amend "$@" ;;
    check)     shift; cmd_check "$@" ;;
    index)     regen_index; echo "$INDEX regenerated" ;;
    *)         sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 1 ;;
esac
