#!/bin/bash
# adr.sh — deterministic operations for .project/adr/ decision records.
# Agents supply the judgment (Decision / Why / Invariants / Alternatives);
# this script owns numbering, status flips, and INDEX.md generation.
# Convention: .project/adr/README.md
#
# Usage:
#   adr.sh new <slug> [--title "..."]   create next entry, print its path
#   adr.sh supersede <old-id> <new-id>  mark old superseded by new
#   adr.sh amend <old-id> <new-id>      record new as amending old
#   adr.sh index                        regenerate INDEX.md from entries
set -euo pipefail

find_project_root() {
    if [ -d ".project" ]; then pwd; return; fi
    local root
    root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
    if [ -n "$root" ] && [ -d "$root/.project" ]; then echo "$root"; return; fi
    echo "Error: no .project/ directory found (run from the repo root)" >&2
    exit 1
}

ROOT="$(find_project_root)"
ADR_DIR="$ROOT/.project/adr"
INDEX="$ADR_DIR/INDEX.md"

# field <file> <key> — read a frontmatter value
field() {
    awk -v key="$2" '
        NR==1 && $0=="---" {infm=1; next}
        infm && $0=="---" {exit}
        infm && index($0, key": ")==1 {sub("^"key": ", ""); print; exit}
    ' "$1"
}

# set_field <file> <key> <value> — replace a frontmatter value in place
set_field() {
    local file="$1" key="$2" value="$3" tmp
    tmp="$(mktemp)"
    awk -v key="$key" -v value="$value" '
        NR==1 && $0=="---" {infm=1; print; next}
        infm && $0=="---" {infm=0; print; next}
        infm && index($0, key": ")==1 {print key": "value; next}
        {print}
    ' "$file" > "$tmp" && mv "$tmp" "$file"
}

# entry_file <id> — resolve an id to its entry path
entry_file() {
    local match
    match="$(compgen -G "$ADR_DIR/$1-*.md" || true)"
    if [ -z "$match" ]; then
        echo "Error: no entry with id $1 in $ADR_DIR" >&2
        exit 1
    fi
    echo "$match" | head -1
}

regen_index() {
    mkdir -p "$ADR_DIR"
    local f id title seams status sup line active_lines="" other_lines=""
    for f in "$ADR_DIR"/[0-9][0-9][0-9][0-9]-*.md; do
        [ -e "$f" ] || continue
        id="$(field "$f" id)"
        title="$(field "$f" title)"
        seams="$(field "$f" seams | tr -d '[]')"
        status="$(field "$f" status)"
        sup="$(field "$f" superseded_by)"
        line="- $id · $title"
        [ -n "$seams" ] && line="$line · seams: $seams"
        if [ "$status" = "superseded" ] && [ "$sup" != "null" ]; then
            line="$line · superseded → $sup"
        elif [ "$status" != "active" ]; then
            line="$line · $status"
        fi
        if [ "$status" = "active" ]; then
            active_lines+="$line"$'\n'
        else
            other_lines+="$line"$'\n'
        fi
    done
    {
        echo "# Decision Records Index"
        echo ""
        echo "<!-- generated by adr.sh — do not hand-edit; run 'adr.sh index' to rebuild -->"
        echo ""
        printf '%s' "$active_lines"
        if [ -n "$other_lines" ]; then
            echo ""
            printf '%s' "$other_lines"
        fi
    } > "$INDEX"
}

next_free_number() {
    local max=0 f n
    for f in "$ADR_DIR"/[0-9][0-9][0-9][0-9]-*.md; do
        [ -e "$f" ] || continue
        n=$((10#$(basename "$f" | cut -c1-4)))
        [ "$n" -gt "$max" ] && max=$n
    done
    local cand=$((max + 1))
    # collision guard for parallel sessions: take the next unclaimed number
    while compgen -G "$ADR_DIR/$(printf '%04d' "$cand")-*.md" >/dev/null; do
        cand=$((cand + 1))
    done
    printf '%04d' "$cand"
}

cmd_new() {
    local slug="${1:?usage: adr.sh new <slug> [--title \"...\"]}"
    shift
    local title=""
    while [ $# -gt 0 ]; do
        case "$1" in
            --title) title="${2:?--title needs a value}"; shift 2 ;;
            *) echo "Error: unknown option $1" >&2; exit 1 ;;
        esac
    done
    [ -n "$title" ] || title="$(echo "$slug" | tr '-' ' ')"
    mkdir -p "$ADR_DIR"
    local id file date owner
    id="$(next_free_number)"
    file="$ADR_DIR/$id-$slug.md"
    date="$(date '+%Y-%m-%d')"
    owner="$(git config --get user.name 2>/dev/null || echo 'unknown')"
    cat > "$file" <<EOF
---
id: $id
title: $title
date: $date
owner: $owner
status: active
amended_by: []
superseded_by: null
provenance: "[AGENT]"
seams: []
supersedes: null
promoted_to: null
---

## Decision

[1-3 sentences: what was decided.]

## Why

[The reasoning a future challenge re-derives against. Required.]

## Invariants established

- [Delete this section if none.]

## Rejected alternatives

- [One-liners, phrased as decision records, never as instructions to future agents.]
EOF
    regen_index
    echo "$file"
}

cmd_supersede() {
    local old_id="${1:?usage: adr.sh supersede <old-id> <new-id>}"
    local new_id="${2:?usage: adr.sh supersede <old-id> <new-id>}"
    local old_file new_file
    old_file="$(entry_file "$old_id")"
    new_file="$(entry_file "$new_id")"
    if [ "$(field "$old_file" status)" = "superseded" ]; then
        echo "Warning: $old_id is already superseded by $(field "$old_file" superseded_by)" >&2
    fi
    set_field "$old_file" status superseded
    set_field "$old_file" superseded_by "$new_id"
    set_field "$new_file" supersedes "$old_id"
    regen_index
    echo "$old_id superseded by $new_id"
}

cmd_amend() {
    local old_id="${1:?usage: adr.sh amend <old-id> <new-id>}"
    local new_id="${2:?usage: adr.sh amend <old-id> <new-id>}"
    local old_file current
    old_file="$(entry_file "$old_id")"
    entry_file "$new_id" >/dev/null
    current="$(field "$old_file" amended_by | tr -d '[]')"
    if [ -n "$current" ]; then
        set_field "$old_file" amended_by "[$current, $new_id]"
    else
        set_field "$old_file" amended_by "[$new_id]"
    fi
    # superseded outranks amended; don't downgrade
    if [ "$(field "$old_file" status)" = "active" ]; then
        set_field "$old_file" status amended
    fi
    regen_index
    echo "$old_id amended by $new_id"
}

case "${1:-}" in
    new)       shift; cmd_new "$@" ;;
    supersede) shift; cmd_supersede "$@" ;;
    amend)     shift; cmd_amend "$@" ;;
    index)     regen_index; echo "$INDEX regenerated" ;;
    *)         sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'; exit 1 ;;
esac
